version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 3000:3000
    depends_on:
      - mongodb
    environment:
      - MONGODB_URI=mongodb://mongodb:27017/applicationUni
  mongodb:
    image: mongo
    ports:
      - 27017:27017
